# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  code:check:
    desc: Check whether code formatting rules apply.
    cmds:
      - poetry run black --check shaclc tests
      - poetry run ruff check shaclc tests

  code:
    desc: Format and standardise code.
    cmds:
      - poetry run black shaclc tests
      - poetry run ruff --fix shaclc tests

  test:
    desc: Run Python tests.
    cmds:
      - poetry run pytest
